version: '3.9'

services:
  main:
    container_name: misa-room
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    command: yarn start
    environment:
      NODE_ENV: 'production'
      APP_PORT: 8080
      REDIS_URL: 'redis://redis:6379'
    expose:
      - 8080
    links:
      - redis
    networks:
      - common

  redis:
    container_name: misa-room-redis
    image: redis:6.2.3-alpine
    ports:
      - 6380:6379
    networks:
      - common

networks:
  common:
